---
title: "Week 7a"
author: Sk Abidur Rahman
---

```{r, eval = FALSE}
install.packages(c("maps", "mapproj", "mapdata"))
```


```{r, warning = FALSE, message = FALSE}
# Load libraries
library(tidyverse)
library(here)
library(maps)
library(mapdata)
library(mapproj)

```


```{r}
# get data for the entire world
world<-map_data("world") #<<

head(world)
```


```{r}
# get data for the USA
usa<-map_data("usa") #<<

head(usa)
```

```{r}
# get data for italy
italy<-map_data("italy") #<<

head(italy)
```


```{r}
# get data for states
states<-map_data("state") #<<

head(states)
```

```{r}
# get data for counties
counties<-map_data("county") #<<

head(counties)
```



```{r}
ggplot()+
  geom_polygon(data = world, aes(x = long, y = lat, group = group)) #<<

```

```{r}
ggplot()+
  geom_polygon(data = world, aes(x = long, y = lat)) #<<

```


```{r plot1, eval=FALSE, warning=FALSE, message=FALSE}
ggplot()+
  geom_polygon(data = world, 
               aes(x = long, y = lat, group = group),
               color = "black") #<<

```
]


```{r plot1-out, ref.label="plot1", echo=FALSE, warning = FALSE}
```


```{r plot1a, eval=FALSE, warning=FALSE, message=FALSE}
ggplot()+
  geom_polygon(data = world, 
               aes(x = long, 
                   y = lat, 
                   group = group, 
                   fill = region),#<<
               color = "black") +
  guides(fill = FALSE)

```

```{r plot1a-out, ref.label="plot1a", echo=FALSE, warning = FALSE}
```


```{r plot2, eval=FALSE, warning=FALSE, message=FALSE}
ggplot()+
  geom_polygon(data = world, 
               aes(x = long, 
                   y = lat,
                   group = group,
                   fill = region),
               color = "black")+
  guides(fill = FALSE)+
  theme_minimal()#<<

```

```{r plot2-out, ref.label="plot2", echo=FALSE, warning = FALSE}
```

```{r plot3, eval=FALSE, warning=FALSE, message=FALSE}
ggplot()+
  geom_polygon(data = world, 
               aes(x = long, 
                   y = lat, 
                   group = group,
                   fill = region),
               color = "black")+
  theme_minimal()+
  guides(fill = FALSE)+
  theme(panel.background = element_rect(fill = "lightblue"))#<<

```

```{r plot3-out, ref.label="plot3", echo=FALSE, warning = FALSE}
```

```{r plot4, eval=FALSE, warning=FALSE, message=FALSE}
ggplot()+
  geom_polygon(data = world, 
               aes(x = long, 
                   y = lat, 
                   group = group,
                   fill = region),
               color = "black")+
  theme_minimal()+
  guides(fill = FALSE)+
  theme(panel.background = element_rect(fill = "lightblue"))+
  coord_map(projection = "mercator", #<<
            xlim = c(-180,180))#<<

```

```{r plot4-out, ref.label="plot4", echo=FALSE, warning = FALSE}
```

```{r plot5, eval=FALSE, warning=FALSE, message=FALSE}
ggplot()+
  geom_polygon(data = world, 
               aes(x = long,
                   y = lat,
                   group = group, 
                   fill = region),
               color = "black")+
  theme_minimal()+
  guides(fill = FALSE)+
  theme(panel.background = element_rect(fill = "lightblue"))+
  coord_map(projection = "sinusoidal", #<<
            xlim = c(-180,180))#<<

```



```{r}
# Use the states dataset
head(states)

```


```{r}
# Use the states dataset
CA_data<-states %>%
  filter(region == "california")
```


```{r plot6, eval=FALSE, warning=FALSE, message=FALSE}
ggplot()+
geom_polygon(data = CA_data, 
             aes(x = long, 
                 y = lat, 
                 group = group), 
             color = "black")+
  coord_map()+
  theme_void() #<<
```



```{r}
# Look at the county data
head(counties)[1:3,] # only showing the first 3 rows for space
```


```{r}
# Look at the county data
head(popdata)
```




```{r}
CApop_county<-popdata %>%
  select("subregion" = County, Population)  %>% # rename the county col
  inner_join(counties) %>%
  filter(region == "california") # some counties have same names in other states

```



```{r}

head(CApop_county)
```


```{r plot7, eval=FALSE, warning=FALSE, message=FALSE}
ggplot()+
geom_polygon(data = CApop_county, 
             aes(x = long, 
                 y = lat, 
                 group = group,
                 fill = Population), #<< 
             color = "black")+
  coord_map()+
  theme_void() 
```

```{r plot7-out, ref.label="plot7", echo=FALSE, warning = FALSE}
```

```{r plot8, eval=FALSE, warning=FALSE, message=FALSE}
ggplot()+
geom_polygon(data = CApop_county, 
             aes(x = long, 
                 y = lat, 
                 group = group,
                 fill = Population),  
             color = "black")+
  coord_map()+
  theme_void() +
  scale_fill_gradient(trans = "log10")#<<
```


```{r plot8-out, ref.label="plot8", echo=FALSE, warning = FALSE}
```

```{r}
head(stars)

```


```{r plot9, eval=FALSE, warning=FALSE, message=FALSE}
ggplot()+
geom_polygon(data = CApop_county, 
             aes(x = long, 
                 y = lat, 
                 group = group,
                 fill = Population),  
             color = "black")+
  geom_point(data = stars, # add a point at all my sites #<<
             aes(x = long, #<<
                 y = lat))+ #<<
  coord_map()+
  theme_void() +
  scale_fill_gradient(trans = "log10")
```


```{r plot9-out, ref.label="plot9", echo=FALSE, warning = FALSE}
```


```{r plot10, eval=FALSE, warning=FALSE, message=FALSE}
ggplot()+
geom_polygon(data = CApop_county, 
             aes(x = long, 
                 y = lat, 
                 group = group,
                 fill = Population),  
             color = "black")+
  geom_point(data = stars, # add a point at all my sites 
             aes(x = long, 
                 y = lat,
                 size = star_no))+ #<<
  coord_map()+
  theme_void() +
  scale_fill_gradient(trans = "log10")
```


```{r plot10-out, ref.label="plot10", echo=FALSE, warning = FALSE}
```


```{r plot11, eval=FALSE, warning=FALSE, message=FALSE}
ggplot()+
geom_polygon(data = CApop_county, 
             aes(x = long, 
                 y = lat, 
                 group = group,
                 fill = Population),  
             color = "black")+
  geom_point(data = stars, # add a point at all my sites 
             aes(x = long, 
                 y = lat,
                 size = star_no))+ 
  coord_map()+
  theme_void() +
  scale_fill_gradient(trans = "log10")+
  labs(size = "# stars/m2") #<<
```


```{r plot11-out, ref.label="plot11", echo=FALSE, warning = FALSE}
```


```{r plot12, eval=FALSE, warning=FALSE, message=FALSE}
ggplot()+
geom_polygon(data = CApop_county, 
             aes(x = long, 
                 y = lat, 
                 group = group,
                 fill = Population),  
             color = "black")+
  geom_point(data = stars, # add a point at all my sites 
             aes(x = long, 
                 y = lat,
                 size = star_no))+ 
  coord_map()+
  theme_void() +
  scale_fill_gradient(trans = "log10")+
  labs(size = "# stars/m2") 
  ggsave(here("Week_07","output","CApop.pdf"))#<<
```


```{r plot12-out, ref.label="plot12", echo=FALSE, warning = FALSE}
```


